logging:
  level:
    ROOT: INFO
    org.springframework.cloud.config.server: DEBUG

server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: file://${pwd}/../
          search-paths: config-repo
          clone-on-start: false
